{% set name = "ez-zarr" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ez_zarr-{{ version }}.tar.gz
  sha256: bd05949b1832e48761cfede5025302ff960f4e987875b74e4014dcc9a5fca022

build:
  entry_points:
    - ez_zarr = ez_zarr.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >={{ python_min }}
    - anndata
    - dask-core
    - numpy
    - pandas
    - zarr
    - matplotlib-base
    - scikit-image
    - rich

test:
  imports:
    - ez_zarr
  commands:
    - pip check
    - ez_zarr --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fmicompbio/ez_zarr
  summary: Give easy, high-level access to ome-zarr filesets.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mbstadler
