{% set name = "ez-zarr" %}
{% set version = "0.3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ez_zarr-{{ version }}.tar.gz
  sha256: d0c40dac76b1eb40a2c2ededc73c98a8b5e28087a902b7eebad55532fd8498cf

build:
  entry_points:
    - ez_zarr = ez_zarr.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - anndata
    - dask-core
    - numpy
    - pandas
    - zarr
    - matplotlib-base
    - scikit-image

test:
  imports:
    - ez_zarr
  commands:
    - pip check
    - ez_zarr --help
  requires:
    - pip

about:
  home: https://github.com/fmicompbio/ez_zarr
  summary: Give easy, high-level access to ome-zarr filesets.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mbstadler
